apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-deployment
  labels:
    component: ms1
spec:
  replicas: 2
  selector:
    matchLabels:
        component: ms1
  template:
    metadata:
      labels:
        component: ms1
    spec:
      containers:
      - name: ms1
        image: sannaman/ms1
        ports:
        - containerPort: 9091