apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-deployment
  labels:
    component: ms2
spec:
  replicas: 2
  selector:
    matchLabels:
        component: ms2
  template:
    metadata:
      labels:
        component: ms2
    spec:
      containers:
      - name: ms2
        image: sannaman/ms2
        ports:
        - containerPort: 9091